# Base image
FROM mohandeepak2002/ignition-test

# Environment variables
ENV GATEWAY_SOFT_KEY=9NBK-P5YV
ENV GATEWAY_ACTIVATION_TOKEN=eyJrdHkiOiJSU0EiLCJraWQiOiI3MmQyMWYzNC0yMmQ2LTRmMmUtYjc3NC1mNTg5MDJk...

# Expose ports for Ignition
EXPOSE 8088 8043 8060

# Persist projects folder
VOLUME /usr/local/bin/data/projects
